model:
  base_learning_rate: 1.0e-6
  target: ldm.models.diffusion.ddpm_condtrain_HDR.LatentRetouchDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: 'gt'
    cond_stage_key: 'txt'
    image_size: 64
    channels: 4
    cond_stage_trainable: false
    conditioning_key: hybrid
    scale_factor: 0.18215
    monitor: val/loss_simple_ema
    use_ema: False

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 7
        out_channels: 8
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 4
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          #attn_type: "vanilla-xformers"
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
            - 1
            - 2
            - 4
            - 4
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.RetouchEmbedder

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    wrap: True
    train:
      target: ldm.data.adobe5k_diff.Adobe5KDataset
      params:
        phase: train
        test_dataset_size: 10
        gt_folder_list: ['01-Experts-A', '02-Experts-B', '03-Experts-C', '04-Experts-D', '05-Experts-E']
    validation:
      target: ldm.data.adobe5k_diff.Adobe5KDataset
      params:
        phase: test
        test_dataset_size: 10


lightning:
  find_unused_parameters: True
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    accumulate_grad_batches: 16